- name: socialnetwork benchmark
  hosts: master
  vars:
    ansible_python_interpreter: /home/XXXX-1/miniconda3/envs/mytunning/bin/python
  tasks:

    - name: docker service rm
      shell:
        cmd: >
          bash rm_services.sh
        chdir: ~/{{ project_name }}/deploy/social_network/scripts


- name: clean up tmp
  hosts: all
  vars:
    benchmark: social_network
  tasks:
    - name: delete tmp
      ansible.builtin.file:
        path: ~/{{ project_name }}/.tmp/.{{ benchmark }}_tmp
        state: absent