---

- name: prepare files
  hosts: all

  vars:
    benchmark: social_network

  tasks:
    - name: check if .tmp exists
      ansible.builtin.stat: path=~/{{ project_name }}/.tmp/.{{ benchmark }}_tmp
      register: tmp_dir

    - name: copy deploy files
      ansible.builtin.copy: src={{ item }} dest=~/{{ project_name }}/.tmp/.{{ benchmark }}_tmp
      with_items:
        - ~/{{ project_name }}/deploy/social_network/ansible/templates
        - ~/{{ project_name }}/deploy/social_network/ansible/volumes
        - ~/{{ project_name }}/deploy/social_network/docker-swarm/volumes/
      when: tmp_dir.stat.exists == False

    - name: generate config from template
      template: src=~/{{ project_name }}/.tmp/.{{ benchmark }}_tmp/templates/{{ item.src }} dest=~/{{ project_name }}/.tmp/.{{ benchmark }}_tmp/{{ item.dest }}
      with_items:
         - { src: swarm.yml.j2, dest: swarm.yml }
         - { src: swarm-frontend.yml.j2, dest: swarm-frontend.yml }
         - { src: parameters-config.txt.j2, dest: config/parameters-config.txt }
         - { src: nginx.conf.j2, dest: nginx-web-server/conf/nginx.conf }
         - { src: compose_post_redis.conf.j2, dest: compose_post_redis.conf }
         - { src: home_timeline_redis.conf.j2, dest: home_timeline_redis.conf }
         - { src: media_mongodb.conf.j2, dest: media_mongodb.conf }
         - { src: post_storage_mongodb.conf.j2, dest: post_storage_mongodb.conf }
         - { src: social_graph_mongodb.conf.j2, dest: social_graph_mongodb.conf }
         - { src: social_graph_redis.conf.j2, dest: social_graph_redis.conf }
         - { src: url_shorten_mongodb.conf.j2, dest: url_shorten_mongodb.conf }
         - { src: user_mongodb.conf.j2, dest: user_mongodb.conf }
         - { src: user_timeline_mongodb.conf.j2, dest: user_timeline_mongodb.conf }
         - { src: user_timeline_redis.conf.j2, dest: user_timeline_redis.conf }


- name: socialnetwork benchmark
  hosts: master
  vars:
    benchmark: social_network
    ansible_python_interpreter: /home/XXXX-1/miniconda3/envs/mytunning/bin/python
  tasks:

    - name: deploy socialnetwork benchmark use docker swarm-frontend
      community.docker.docker_stack:
        name: sn
        state: present
        compose:
          - ~/{{ project_name }}/.tmp/.{{ benchmark }}_tmp/swarm-frontend.yml

    - name: deploy socialnetwork benchmark use docker swarm
      community.docker.docker_stack:
        name: sn
        state: present
        compose:
          - ~/{{ project_name }}/.tmp/.{{ benchmark }}_tmp/swarm.yml

    - name: wait for 30 seconds
      ansible.builtin.wait_for:
        timeout: 90

    - name: create output dir
      ansible.builtin.file:
        path: ~/{{ project_name }}/.tmp/.{{ benchmark }}_tmp/output
        state: directory