CREATE DATABASE ycsb;

USE ycsb;

DROP TABLE IF EXISTS usertable;

CREATE TABLE usertable(YCSB_KEY VARCHAR(255) PRIMARY KEY,
  FIELD0 VARCHAR(255), FIELD1 VARCHAR(255),
  FIELD2 VARCHAR(255), FIELD3 VARCHAR(255),
  FIELD4 VARCHAR(255), FIELD5 VARCHAR(255),
  FIELD6 VARCHAR(255), FIELD7 VARCHAR(255),
  FIELD8 VARCHAR(255), FIELD9 VARCHAR(255));

CREATE USER 'exporter'@'%' IDENTIFIED BY '123456';
GRANT PROCESS, REPLICATION CLIENT ON *.* TO 'exporter'@'%';
GRANT SELECT ON performance_schema.* TO 'exporter'@'%';